name: Update Helios Data Core

on:
  workflow_dispatch:
  schedule:
    # Runs every minute
    - cron: '*/1 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Harvester to update data.json
        run: python helios_harvester.py

      - name: Commit and push if data changed
        run: |
          git config --global user.name "Helios Harvester"
          git config --global user.email "actions@github.com"
          git add data.json
          # Commit only if there are changes
          git diff --staged --quiet || git commit -m "Update data core"
          git push