name: Update Helios Data Core

on:
  # This new line adds a trigger to run the workflow on every push to the main branch.
  push:
    branches: [ main ]
    
  workflow_dispatch:
  schedule:
    # This keeps the 5-minute schedule as a backup.
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Preserve previous data file for AI analysis
        run: mv data.json data_previous.json || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Harvester to generate new data.json
        run: python helios_harvester.py

      - name: Commit and push if data changed
        run: |
          git config --global user.name "Helios Chronos Engine"
          git config --global user.email "actions@github.com"
          git add data.json data_previous.json
          git diff --staged --quiet || git commit -m "Update data core via Chronos Engine"
          git push